name = "id.haijetcop.my.id"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008" //domain = haijetcop.my.id
UUID = "1c5f30c2-c760-11ef-9cd2-0242ac120002"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
